openapi: 3.0.1
info:
  title: Auth API
  description: API documentation for user authentication and token generation.
  version: 1.0.0
servers:
  - url: http://161.97.109.65:3000/
tags:
  - name: Authentication
    description: Operations related to user authentication

paths:
  /api/auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                username:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                password:
                  type: string
                address:
                  type: string
              required:
                - firstname
                - lastname
                - username
                - email
                - phone
                - password
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: User created successfully
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      firstname:
                        type: string
                      lastname:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                      address:
                        type: string
                      avatar:
                        type: string
                      token:
                        type: string
                  token:
                    type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error

  /api/auth/login:
    post:
      tags:
        - Authentication
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Login successful
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      firstname:
                        type: string
                      lastname:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                      address:
                        type: string
                      avatar:
                        type: string
                      token:
                        type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

  /api/auth/generateToken:
    post:
      tags:
        - Authentication
      summary: Generate a never-expiring token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: Token generation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Login successful
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      firstname:
                        type: string
                      lastname:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                      address:
                        type: string
                      avatar:
                        type: string
                      token:
                        type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        username:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
        avatar:
          type: string
        token:
          type: string
