openapi: 3.0.3
info:
  title: Cart API
  description: API for managing the user's cart
  version: 1.0.0
servers:
  - url: http://161.97.109.65:3000
paths:
  /api/cart:
    get:
      summary: View cart
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful retrieval of cart items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CartItem"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

    post:
      summary: Add an item to the cart
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  example: 60d0fe4f5311236168a109ca
      responses:
        "200":
          description: Item added to cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Item added to cart
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /api/cart/{productId}:
    delete:
      summary: Remove an item from the cart
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            example: 60d0fe4f5311236168a109ca
      responses:
        "200":
          description: Item removed from cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Item removed from cart
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

    put:
      summary: Update a cart item
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            example: 60d0fe4f5311236168a109ca
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  example: 60d0fe4f5311236168a109ca
      responses:
        "200":
          description: Cart item updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Cart item updated
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /api/cart/checkout:
    post:
      summary: Checkout the cart
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Checkout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Checkout successful
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CartItem:
      type: object
      properties:
        productId:
          type: string
          example: 60d0fe4f5311236168a109ca
        name:
          type: string
          example: iPhone 12
        description:
          type: string
          example: A powerful phone with great camera capabilities.
        price:
          type: number
          format: float
          example: 999.99
        quantity:
          type: integer
          example: 1
