openapi: 3.0.3
info:
  title: Conversation API
  description: API for managing conversations
  version: 1.0.0
servers:
  - url: http://161.97.109.65:3000
paths:
  /api/conversations:
    post:
      summary: Create a new conversation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                participants:
                  type: array
                  items:
                    type: string
                  example: ["60d0fe4f5311236168a109ca", "60d0fe4f5311236168a109cb"]
      responses:
        "201":
          description: Conversation created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conversation"
        "400":
          description: Bad request, invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: One or more participants are not registered users.
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /api/conversations/{userId}:
    get:
      summary: Get conversations for a user
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: 60d0fe4f5311236168a109ca
      responses:
        "200":
          description: Successful retrieval of conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Conversation"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /api/conversations/messages:
    post:
      summary: Send a message to a seller
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversationId:
                  type: string
                  example: 60d0fe4f5311236168a109ca
                sender:
                  type: string
                  example: 60d0fe4f5311236168a109cb
                content:
                  type: string
                  example: "Is this product still available?"
                productImage:
                  type: string
                  example: "/uploads/product.jpg"
      responses:
        "201":
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "404":
          description: Conversation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Conversation not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Conversation:
      type: object
      properties:
        _id:
          type: string
          example: 60d0fe4f5311236168a109ca
        participants:
          type: array
          items:
            type: string
          example: ["60d0fe4f5311236168a109ca", "60d0fe4f5311236168a109cb"]
        lastMessage:
          type: string
          example: No messages yet.
        lastMessageAt:
          type: string
          format: date-time
          example: 2021-06-22T12:34:56Z
    Message:
      type: object
      properties:
        _id:
          type: string
          example: 60d0fe4f5311236168a109cd
        conversationId:
          type: string
          example: 60d0fe4f5311236168a109ca
        sender:
          type: string
          example: 60d0fe4f5311236168a109cb
        content:
          type: string
          example: Is this product still available?
        productImage:
          type: string
          example: /uploads/product.jpg
        createdAt:
          type: string
          format: date-time
          example: 2021-06-22T12:34:56Z
