openapi: 3.0.3
info:
  title: Interaction API
  description: API for managing user interactions
  version: 1.0.0
servers:
  - url: http://161.97.109.65:3000
paths:
  /api/interactions:
    get:
      summary: Get all interactions
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful retrieval of interactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  interactions:
                    type: array
                    items:
                      $ref: "#/components/schemas/Interaction"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

    post:
      summary: Track a new interaction
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: 60d0fe4f5311236168a109ca
                productId:
                  type: string
                  example: 60d0fe4f5311236168a109cb
                interactionType:
                  type: string
                  example: addToCart
                interactionValue:
                  type: integer
                  example: 1
      responses:
        "201":
          description: Interaction tracked successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Interaction"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /api/interactions/user/{userId}:
    get:
      summary: Get interactions for a user
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: 60d0fe4f5311236168a109ca
      responses:
        "200":
          description: Successful retrieval of user interactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  interactions:
                    type: array
                    items:
                      $ref: "#/components/schemas/Interaction"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /api/interactions/download:
    get:
      summary: Download all interactions
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful download of interactions
          content:
            application/json:
              schema:
                type: string
                format: binary
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Interaction:
      type: object
      properties:
        _id:
          type: string
          example: 60d0fe4f5311236168a109cc
        userId:
          type: string
          example: 60d0fe4f5311236168a109ca
        productId:
          type: string
          example: 60d0fe4f5311236168a109cb
        interactionType:
          type: string
          example: addToCart
        interactionValue:
          type: integer
          example: 1
        createdAt:
          type: string
          format: date-time
          example: 2021-06-22T12:34:56Z
