openapi: 3.0.3
info:
  title: Message API
  description: API for managing messages in conversations
  version: 1.0.0
paths:
  /messages/{conversationId}:
    get:
      summary: Get messages in a conversation
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            example: 60d0fe4f5311236168a109cc
      responses:
        "200":
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: 60d0fe4f5311236168a109cd
                    conversationId:
                      type: string
                      example: 60d0fe4f5311236168a109cc
                    sender:
                      type: string
                      example: 60d0fe4f5311236168a109ca
                    content:
                      type: string
                      example: Hello, I'm interested in your product.
                    productImage:
                      type: string
                      example: "/uploads/product_image.jpg"
                    sentAt:
                      type: string
                      format: date-time
                      example: "2024-05-31T12:00:00Z"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /messages:
    post:
      summary: Send message in conversation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversationId:
                  type: string
                  example: 60d0fe4f5311236168a109cc
                sender:
                  type: string
                  example: 60d0fe4f5311236168a109ca
                content:
                  type: string
                  example: Hello, I'm interested in your product.
                productImage:
                  type: string
                  example: "/uploads/product_image.jpg"
      responses:
        "201":
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: 60d0fe4f5311236168a109cd
                  conversationId:
                    type: string
                    example: 60d0fe4f5311236168a109cc
                  sender:
                    type: string
                    example: 60d0fe4f5311236168a109ca
                  content:
                    type: string
                    example: Hello, I'm interested in your product.
                  productImage:
                    type: string
                    example: "/uploads/product_image.jpg"
                  sentAt:
                    type: string
                    format: date-time
                    example: "2024-05-31T12:00:00Z"
        "404":
          description: Conversation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Conversation not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
