openapi: 3.0.3
info:
  title: Wishlist API
  description: API for managing wishlists
  version: 1.0.0
servers:
  - url: http://161.97.109.65:3000
paths:
  /api/wishlist:
    post:
      summary: Add product to wishlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: 60d0fe4f5311236168a109cc
                productId:
                  type: string
                  example: 60d0fe4f5311236168a109dd
              required:
                - userId
                - productId
      responses:
        "200":
          description: Product added to wishlist successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wishlist"
        "404":
          description: Product or wishlist not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

    delete:
      summary: Remove product from wishlist
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
            example: 60d0fe4f5311236168a109cc
        - name: productId
          in: query
          required: true
          schema:
            type: string
            example: 60d0fe4f5311236168a109dd
      responses:
        "200":
          description: Product removed from wishlist successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wishlist"
        "404":
          description: Wishlist not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Wishlist not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /api/wishlist/{userId}:
    get:
      summary: Get wishlist by user ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: 60d0fe4f5311236168a109cc
      responses:
        "200":
          description: Successful retrieval of wishlist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wishlist"
        "404":
          description: Wishlist not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Wishlist not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

components:
  schemas:
    Wishlist:
      type: object
      properties:
        userId:
          type: string
          example: 60d0fe4f5311236168a109cc
        items:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
                example: 60d0fe4f5311236168a109dd
      required:
        - userId
        - items
